Fix issue with spaces in filenames
losoliveirasilva/rofigen pull request #5
Opened 2022-10-12 14:54 UTC by Nmoleo64

Related to issue #4 

If the path of the script I am passing to rofigen.sh has a space in it, the script breaks even if I use a backslash or double/single quotes to escape it.

The issue appears to be line 3 of rofigen: source $1

I replaced it with source "$1" and that fixed the issue for me,

2022-10-12 17:43 UTC, losoliveirasilva requested changes

2022-10-12 17:43 UTC, losoliveirasilva commented on rofigen
> +"source $1"
Are you sure it's `"source $1"`, not `source "$1"`?

2022-10-12 19:15 UTC, Nmoleo64 commented
You're right, it should be `source "$1"`. I wasn't paying enough attention. Sorry about that!

I created another commit and it appears to show in the PR here

2022-10-13 14:17 UTC, losoliveirasilva approved these changes

2022-10-13 14:17 UTC, merged